--------------------------------------------------------
--  파일이 생성됨 - 금요일-12월-15-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "C##JSP"."MEMBER" 
   (	"ID" VARCHAR2(50 BYTE), 
	"PASSWD" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(20 BYTE), 
	"REG_DATE" TIMESTAMP (6), 
	"ADDRESS" VARCHAR2(100 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"TEL" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##JSP.MEMBER
SET DEFINE OFF;
Insert into C##JSP.MEMBER (ID,PASSWD,NAME,REG_DATE,ADDRESS,EMAIL,TEL) values ('esef','1122','김폴리',to_timestamp('23/12/15 14:46:45.932000000','RR/MM/DD HH24:MI:SSXFF'),'서울 특별시 ','asdf1122@naver','010-1234-1234');
Insert into C##JSP.MEMBER (ID,PASSWD,NAME,REG_DATE,ADDRESS,EMAIL,TEL) values ('ddd','1234','토토',to_timestamp('23/12/15 14:50:14.095000000','RR/MM/DD HH24:MI:SSXFF'),'서울 특별시 ','asewr12@naver','010-1231-1231');
--------------------------------------------------------
--  DDL for Index SYS_C008380
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##JSP"."SYS_C008380" ON "C##JSP"."MEMBER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "C##JSP"."MEMBER" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##JSP"."MEMBER" MODIFY ("PASSWD" NOT NULL ENABLE);
  ALTER TABLE "C##JSP"."MEMBER" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "C##JSP"."MEMBER" MODIFY ("REG_DATE" NOT NULL ENABLE);
  ALTER TABLE "C##JSP"."MEMBER" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##JSP"."MEMBER" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "C##JSP"."MEMBER" MODIFY ("TEL" NOT NULL ENABLE);
  ALTER TABLE "C##JSP"."MEMBER" MODIFY ("ADDRESS" NOT NULL ENABLE);
